### ISSUE TITLE
Testing Task List

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/cbf-clean#12]
### By Users
- [x] Give a few questions to users for UAT: submit a few forms, filter some cities, download and check out .csv. Ask for their response to those questions. (google form, or wufoo, or just email?)
### By Dev's
- [x] Add (thousand) records and test page load and csv on mobile and slower pc
- [x] Test on common browsers back to IE 7. Maybe use www.browserstack.com
- [x] Test bad users: back buttons, refresh on form submit, google meteor security
